import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { UserProvider } from "@auth0/nextjs-auth0/client";
import { Providers } from "@/app/providers";
import Navbar from "@/app/components/navbar";
import React from "react";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <Providers>
            <Navbar />
            <main>{children}</main>
            <Footer />
          </Providers>
        </body>
      </UserProvider>
    </html>
  );
}
